#!/usr/bin/env python3

import sys, os

from PyQt6.QtWidgets import QApplication, QMainWindow
from PyQt6 import uic
from PyQt6.QtCore import QTimer

# disable cache usage must be before any local imports
sys.dont_write_bytecode = True

import linuxcnc

from libemc import connections
from libemc import commands

class main(QMainWindow):
	def __init__(self):
		super().__init__()
		path = os.path.dirname(os.path.realpath(sys.argv[0]))
		lib_path = os.path.join(path, 'libemc')
		stylesheet = os.path.join(lib_path, 'emc.qss')
		with open(stylesheet,'r') as fh:
			self.setStyleSheet(fh.read())
		self.status = linuxcnc.stat()
		self.status.poll()
		#print(self.status.ini_filename)
		inifile = linuxcnc.ini(self.status.ini_filename)

		gui = inifile.find('DISPLAY', 'GUI') or False
		if gui:
			gui_path = os.path.join(os.path.dirname(self.status.ini_filename), gui)
			if os.path.isfile(gui_path):
				print(f'Using GUI: {gui_path}')
			else:
				gui_path = os.path.join(path, 'emc.ui')
		print(gui_path)

		uic.loadUi(gui_path, self)
		#self.setGeometry(50, 50, 500, 300)
		#self.setWindowTitle("EMC GUI 6")
		connections.connect(self)
		#machine_name = inifile.find("EMC", "MACHINE") or "unknown"
		#print(f'{machine_name}')
		#gui_path = inifile.find('DISPLAY', 'DISPLAY_PATH') or 'none'
		#print(gui_path)
		self.timer = QTimer()
		self.timer.timeout.connect(self.update_status)
		self.timer.start(100)
		self.show()

	def update_status(self):
		self.status.poll()
		#print('updated')
		self.estop_status_lb.setText(f'{self.status.estop}')

if __name__ == '__main__':
	app = QApplication(sys.argv)
	gui = main()
	sys.exit(app.exec())
