#!/usr/bin/env python3

import sys, os

from PyQt6.QtWidgets import QApplication, QMainWindow
from PyQt6 import uic
from PyQt6.QtCore import QTimer

# disable cache usage must be before any local imports
sys.dont_write_bytecode = True

import linuxcnc

from libemc import connections
from libemc import commands

class main(QMainWindow):
	def __init__(self):
		super().__init__()
		base = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), ".."))
		libdir = os.path.join(base, "lib", "libemc")
		datadir = os.path.join(base, "share", "linuxcnc")
		print(base)
		print(libdir)
		print(datadir)
		uic.loadUi(os.path.join(libdir, 'emc.ui'), self)
		#self.setGeometry(50, 50, 500, 300)
		self.setWindowTitle("EMC GUI 6")
		connections.connect(self)
		self.emc = commands.emc_control(self, linuxcnc)
		self.status = linuxcnc.stat()
		self.timer = QTimer()
		self.timer.timeout.connect(self.update_status)
		self.timer.start(1000)
		self.show()

	def update_status(self):
		self.status.poll()
		print('updated')
		self.estop_status_lb.setText(f'{self.status.estop}')

if __name__ == '__main__':
	app = QApplication(sys.argv)
	gui = main()
	sys.exit(app.exec())
